# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recalls',
            fields=[
                ('record_id', models.IntegerField(db_column='RECORD_ID', primary_key=True, serialize=False)),
                ('campno', models.TextField(blank=True, db_column='CAMPNO', null=True)),
                ('maketxt', models.TextField(blank=True, db_column='MAKETXT', null=True)),
                ('modeltxt', models.TextField(blank=True, db_column='MODELTXT', null=True)),
                ('yeartxt', models.IntegerField(blank=True, db_column='YEARTXT', null=True)),
                ('mfgcampno', models.TextField(blank=True, db_column='MFGCAMPNO', null=True)),
                ('compname', models.TextField(blank=True, db_column='COMPNAME', null=True)),
                ('mfgname', models.TextField(blank=True, db_column='MFGNAME', null=True)),
                ('bgman', models.FloatField(blank=True, db_column='BGMAN', null=True)),
                ('endman', models.FloatField(blank=True, db_column='ENDMAN', null=True)),
                ('rcltypecd', models.TextField(blank=True, db_column='RCLTYPECD', null=True)),
                ('potaff', models.FloatField(blank=True, db_column='POTAFF', null=True)),
                ('odate', models.FloatField(blank=True, db_column='ODATE', null=True)),
                ('influenced', models.IntegerField(blank=True, db_column='INFLUENCED', null=True)),
                ('mfgtxt', models.TextField(blank=True, db_column='MFGTXT', null=True)),
                ('rcdate', models.FloatField(blank=True, db_column='RCDATE', null=True)),
                ('datea', models.IntegerField(blank=True, db_column='DATEA', null=True)),
                ('rpno', models.FloatField(blank=True, db_column='RPNO', null=True)),
                ('fmvss', models.TextField(blank=True, db_column='FMVSS', null=True)),
                ('desc_defect', models.TextField(blank=True, db_column='DESC_DEFECT', null=True)),
                ('conequence_defect', models.TextField(blank=True, db_column='CONEQUENCE_DEFECT', null=True)),
                ('corrective_action', models.TextField(blank=True, db_column='CORRECTIVE_ACTION', null=True)),
                ('notes', models.TextField(blank=True, db_column='NOTES', null=True)),
                ('rcl_cmpt_id', models.FloatField(blank=True, db_column='RCL_CMPT_ID', null=True)),
            ],
            options={
                'db_table': 'recalls',
                'managed': False,
            },
        ),
    ]
